import type { Metadata } from "next";
import "./globals.css";
import TopHeader from "@/components/topheader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" antialiased bg-fuchsia-100 ">
        <TopHeader />
        {children}
      </body>
    </html>
  );
}
